### ISSUE TITLE
retention - email notifications for items to be removed

### ISSUE THREAD

**Issue by phette23** [cca/equella_scripts#11]
Create a bulk email notice routine, perhaps similar to how we do syllabus reminders. High-level outline:

- [x] iterate over all the items to be removed
- [x] collect them into buckets for each owner (question for the future when collaborators start to appear: do we email all collaborators of an item or only the true owner? probably has to be everyone)
- [x] format an email to the owner with a list of their items that will be removed and link to the Retention Policy
- [x] include [instructions on how to export](https://github.com/cca/equella_scripts/issues/10) these items
- [x] ensure the mail routine can scale to hundreds or thousands of messages (use Mailgun?)

## Questions

Who should the email's reply-to address be? Probably vault@cca.edu right? We are talking about tens of thousands of items and thousands of users, individualized support will not be possible.

The syllabus reminders use a Python SMTP script run from a local development web server so that they are not flagged by Google as suspicious. However, we would really like to avoid an additional language/tech stack in this project, which is committed to using Node. We need to test and find an SMTP library for Node that can send emails without them being flagged by Google.

Bonus: HTML formatted emails instead of plain text. We could hyperlink item titles instead of printing out their gross-looking URLs.

**Comment by phette23** [comment]
I'm still waiting on some communications feedback from Annemarie but this part is close to done.

**Comment by phette23** [comment]
Found and fixed one problem - an email to an invalid address (happened to be an empty username string) will fail and cause the whole program to stop. Unfortunately, it still seems that _any_ failed email breaks the process. Sending 100 emails at once, I received this error and it looks like none went out:

```
/Users/ephetteplace/Code/aVAULT/equella_scripts/node_modules/nodemailer/lib/smtp-connection/index.js:784
            err = new Error(message);
                  ^

Error: Data command failed: 421 4.3.0 Temporary System Problem.  Try again later (10). k202-20020a6284d3000000b0050dc76281b4sm14053056pfd.142 - gsmtp
    at SMTPConnection._formatError (/Users/ephetteplace/Code/aVAULT/equella_scripts/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._actionDATA (/Users/ephetteplace/Code/aVAULT/equella_scripts/node_modules/nodemailer/lib/smtp-connection/index.js:1650:34)
    at SMTPConnection.<anonymous> (/Users/ephetteplace/Code/aVAULT/equella_scripts/node_modules/nodemailer/lib/smtp-connection/index.js:1622:26)
    at SMTPConnection._processResponse (/Users/ephetteplace/Code/aVAULT/equella_scripts/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)
    at SMTPConnection._onData (/Users/ephetteplace/Code/aVAULT/equella_scripts/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)
    at TLSSocket.SMTPConnection._onSocketData (/Users/ephetteplace/Code/aVAULT/equella_scripts/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10) {
  code: 'EENVELOPE',
  response: '421 4.3.0 Temporary System Problem.  Try again later (10). k202-20020a6284d3000000b0050dc76281b4sm14053056pfd.142 - gsmtp',
  responseCode: 421,
  command: 'DATA'
}
```

Looks like gmail predictable does not like 100 emails sent out in under a second. I'll put a pause in between each email to see if that helps, though I'm still worried that one failed message in the middle will break everything. Maybe the calls to `mailUser` in contact.js need to be wrapped in a try-catch block.

**Comment by phette23** [comment]
This article may also be useful: https://support.google.com/mail/answer/81126?hl=en&vid=0-147038839700-1476339994156
